@startuml

class Branch {

   
}

class Employee {


}

class ListAllEmployeesUI {

    

}

class ListAllEmployeesController {

  
}

class BranchRepository {

    +getAllBranches()
    +sortBranchesByListings(Branches)
    +getListingTotalByBranch(ID)
    
}

class EmployeeRepository {

    +getEmployeesByBranchID(ID)
    +sortEmployeesAlphabetically(Employees)

}


class Repositories {

    +getInstance()
    +getEmployeeRepository()
    +getBranchRepository()

}


ListAllEmployeesUI -[dashed]-> ListAllEmployeesController
ListAllEmployeesController-[dashed]-> Repositories
ListAllEmployeesController-[dashed]-> BranchRepository
ListAllEmployeesController-[dashed]-> EmployeeRepository


Repositories -> Repositories : Instance
Repositories --> "1" EmployeeRepository
Repositories --> "1" BranchRepository




BranchRepository -down-> "*" Branch
EmployeeRepository -down-> "*" Employee

Branch "1" -right-> "*" Employee : employes


@enduml