@startuml

actor Client as client
participant SYSTEM as ui

autonumber

activate client
activate ui

client -> ui: starts to read the response for the appointment request

ui -> client: shows appointment request

ui -> client: asks the user to accept or reject

client -> ui: rejects the request

ui -> client: asks the user to specify a reason for rejecting the appointment request

client -> ui: types the reason for for rejecting the appointment request

ui -> client: asks confirmation

client -> ui: confirms

ui -> client: informs the operation success


@enduml