@startuml

actor Client as client
participant SYSTEM as ui

autonumber

activate client
activate ui

client -> ui: starts to read the response for the appointment request

ui -> client: shows appointment request

ui -> client: asks the user to accept

client -> ui: accepts the request

ui -> client: asks confirmation

client -> ui: confirms

ui -> client: informs the operation success

@enduml