@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class PublishAnnouncementUI{
}

class PublishAnnouncementController {
    + PublishAnnouncementController(date,Property,commission,agentName)
    + createAnnouncement(date,Property,commission,agentName)
    + createNotification(ownerName, ownerPhoneNumber,ID,date,agentName,agentPhoneNumber)
    - getEmployeeFromSession()
    - getCityList()

}

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserNameByEmail()
}




class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getAnnouncementRepository()
    +getEmployeeRepository()
}

class AnnouncementRepository{
    +getAnnouncement()
    +validateAnnouncement()
    +addAnnouncement()
}

class CityRepository{
    +getCityList()

}
class EmployeeRepository{
    +getAgentPhoneNumber()

}

class Announcement{
    + Announcement(date,Property,commission,agentName,owner)

}

class Property{
  -TypeOfBusiness TypeOfBusiness
  -float size
  -string location
  -float distance_from_the_city_center
  -String photographs
  -float price
  -int numberOfMonthsRent

}
class House{
    -numberOfBedrooms
    -numberOfBathrooms
    -availableEquipments
    -numberOfParkingSpaces
    -sunExposure
    -existenceOfBasement
    -inhabitableLoft

}

class Apartment{
    -numberOfBedrooms
    -numberOfBathrooms
    -availableEquipments
    -numberOfParkingSpaces
}

class Land{
}




class Agent {
    -citizenCard
    -taxNumber
    -address
    -phoneNumber
    -agency
    -email
    +publishAnnouncement(date,Property,commission,agentName)
}
class NotificationService{

    +CreateNotification()
    +SendSMS()
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance
PublishAnnouncementController .> Repositories : repositories

Repositories --> "1" EmployeeRepository
Repositories --> "1" CityRepository


EmployeeRepository --> "*" Agent: Agent
ApplicationSession --> "1" UserSession : userSession

PublishAnnouncementController ..> "1" Agent : Agent
PublishAnnouncementController ..> ApplicationSession
PublishAnnouncementController ..> UserSession

PublishAnnouncementUI .> PublishAnnouncementController


PublishAnnouncementController ..> AnnouncementRepository : AnnouncementRepository

PublishAnnouncementController ..> CityRepository : CityRepository

AnnouncementRepository --> "*" Announcement

Announcement "1" --> "1" Property: property

Property "1" --> "1" House: house
Property "1" --> "1" Apartment: apartment
Property "1" --> "1" Land: land
PublishAnnouncementController --> NotificationService: notificationService

Announcement --> Agent : publishedBy
@enduml