@startuml
autonumber
actor "Unregistered User" as UR
participant ":System" as SYS
activate UR
UR -> SYS: starts listing announcements
activate SYS
return shows available fields and requests data selection (buy/rent, type of property, no. of rooms)
deactivate SYS

alt
    loop
    UR -> SYS: selects required data (buy/rent, type of property, no. of rooms)
    UR <-- SYS: shows matching announcements
    end
else
    UR -> SYS: doesn't select any data
    UR <-- SYS: shows all announcements
end
loop
    UR -> SYS: selects sorting order (price and/or location)
    UR <-- SYS: displays sorted data as requested
end


@enduml
