@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class PublishAnnouncementUI{
}

class PublishAnnouncementController {
    + PublishAnnouncementController(Property)
    + createAnnouncment(Bussiness,size,location,distance_from_the_city_center,\nprice,commission, Agency, Agent)
    - getAgentFromSession()

}

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}


class AgencyRepository {
    + getAgencyByAgentEmail(email)
}

class Agency {
    - String name
    + anyEmployeeHasEmail(email)
    + Agency(name)
    - getAgentByEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getAgencyRepository()
}

class AnnouncementRepository{
    +getAnnouncement()
    +validateAnnouncement()
    +addAnnouncement()
}

class Announcement{
    + Announcement(Business,size,location,distance_from_the_city_center,\nprice,commission)

}

class Property{
  -String Business
  -float size
  -string location
  -float distance_from_the_city_center
  -float price
}



class Agent {
    -citizenCard
    -taxNumber
    -address
    -phoneNumber
    -agency
    -email
    +publishAnnouncement(Business,size,location,distance_from_the_city_center,\nprice,commission)
}



Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance
PublishAnnouncementController .> Repositories : repositories

Repositories --> "1" AgencyRepository

AgencyRepository --> "*" Agency
ApplicationSession --> "1" UserSession : userSession

PublishAnnouncementController ..> "1" Agency : Agency
PublishAnnouncementController ..> ApplicationSession
PublishAnnouncementController ..> UserSession

PublishAnnouncementUI .> PublishAnnouncementController

PublishAnnouncementController ..> Property

PublishAnnouncementController ..> AnnouncementRepository : AnnouncementRepository

AnnouncementRepository --> "*" Announcement

Announcement "1" --> "1" Property: property

Announcement --> Agent : publishedBy
@enduml