@startuml
autonumber
actor "Administrator" as OE

activate OE
OE -> ":System" : want to specify a new location
activate ":System"
":System" --> OE : requests data related to the state

deactivate ":System"

OE -> ":System" : types requested data
activate ":System"
":System" --> OE : confirms the data and asks for the data related to the City
deactivate ":System"
OE -> ":System" : types requested data
activate ":System"
":System" --> OE : confirms the data and asks for the data related to the District
deactivate ":System"
OE -> ":System" : types requested data
activate ":System"
":System" --> OE : confirms the data and asks for the data related to the Street
deactivate ":System"
OE -> ":System" : types requested data
activate ":System"
":System" --> OE : confirms the data and asks for the data related to the Zipcode
deactivate ":System"
OE -> ":System" : types requested data
activate ":System"
":System" --> OE : creates the location  and confirm the success of the operation
@enduml