@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Agent {
    citizen card
    tax number
    address
    phone number
    agency
}

class Advertisement {
    property description
}



class House {
     number of bedrooms
     number of bathroom
     number of parking spaces
     available equipment
     existence of a basement
     inhabitable loft
     sun exposure
}

class Apartment {
     number of bedrooms
     number of bathroom
     number of parking spaces
     available equipment
}
class Land {
     description
}

class Commission {
    commission value
}

class Property {
     type of property
     area
     location
     distance from the city centre
     price
     photographs
}

class User {
    name
    e-mail
    password

}

class PropertyOwner {
    phone number

}


Advertisement "*" -- "*" Property: contains >
PropertyOwner "*" --"*" Property: it has >
User "*" - "*" PropertyOwner: can be >
Agent "*" - "*" Property: register >
Agent "*" - "*" Advertisement: publish >
User "*"  - "*" Agent: can be >
House "*" - "*" Property: is >
Apartment"*" - "*" Property: is >


@enduml