@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Agent {
    citizen card
    tax number
    address
    phone number
    agency
}

class Advertisement {
    property description
}



class House {
     number of bedrooms
     number of bathroom
     number of parking spaces
     available equipment
     existence of a basement
     inhabitable loft
     sun exposure
}

class Apartment {
     number of bedrooms
     number of bathroom
     number of parking spaces
     available equipment
}
class Land {
     description
}

class Commission {
    commission value
}

class Property {
     type of property
     area
     location
     distance from the city centre
     price
     photographs
}

class User {
    name
    e-mail
    password

}

class PropertyOwner {
    phone number

}


Advertisement "*" -- "*" Property: contains >
PropertyOwner "1" --"*" Property: it has >
User "1" - "1" PropertyOwner: can be >
Agent "1" - "*" Property: register >
Agent "1" -- "*" Advertisement: publish >
User "1"  - "1" Agent: can be >
House "1" --"1" Property: is >
Apartment"1" -- "1" Property: is >
Land"1" - "1" Property: is >
Advertisement"1" - "1" Commission: it has >




@enduml