@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


skinparam classAttributeIconSize 0

hide circle
hide methods

class Owner {
}

class Property {
    - String sellOrRent
    - String typeProperty
    - int bedrooms
    - int bathrooms
    - int parking
    - String equipment
    - boolean basement
    - boolean inhabitalLoft
    - boolean sunExposure
    - int area
    - String location
    - int  centreDistance
    - double price
    - String photographs
    - Agent agentList
}

Owner "1" - "*" Property: registers >
@enduml