@startuml

autonumber

actor Client as client
participant ScheduleVisitUI as ui
participant ScheduleVisitController as ctrl
participant AnnouncementMapper as mapper
participant AnnouncementDTO
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as rep
participant AnnouncementRepository
participant ScheduleRepository
participant Schedule as schedule

autonumber

activate client

client -> ui: starts scheduling request

activate ui



ui-> client: requests the property business he wants to schedule (Sell, Rent or All)
client->ui: selects the type of business

ui -> ctrl** : create
ctrl -> RepositorySingleton: getInstance()
activate ctrl
activate RepositorySingleton
RepositorySingleton --> ctrl: return repositories
deactivate RepositorySingleton

ctrl-> rep: getAnnouncementRepository()
activate rep
rep-->ctrl: return AnnouncementRepository
deactivate rep


ui -> ctrl: getAnnouncementList()

ctrl -> AnnouncementRepository: getAnnouncementList()

activate AnnouncementRepository


AnnouncementRepository -> AnnouncementDTO: return AnnouncementList

deactivate AnnouncementRepository

activate AnnouncementDTO

AnnouncementDTO -> mapper:  return AnnouncementList
activate mapper
mapper -> ctrl: return AnnouncementList
deactivate mapper

deactivate AnnouncementDTO



ctrl -> ui: return AnnouncementList


ui -> client: shows announcement list and requests the user to select one\n and insert all the information (day, beginHour,endHour, note)

client -> ui: selects announcement with the property and types all the information

ui -> ctrl: createSchedule()

ctrl -> ScheduleRepository: validateScheduleHour()

activate ScheduleRepository
ScheduleRepository->ctrl: return bolean
deactivate ScheduleRepository
ctrl -> schedule: createSchedule()


activate schedule

schedule -> schedule: validates the schedule

schedule -> ctrl: return schedule

deactivate schedule


ctrl -> ui: return schedule


ui -> client: shows request schedule information

client -> ui: confirms the data

ui -> ctrl: saveScheduleSchedule()

ctrl -> ScheduleRepository: saveSchedule()
activate ScheduleRepository

ScheduleRepository-> ScheduleRepository: addSchedule()

deactivate ScheduleRepository



ui -> client: informs operation sucess


deactivate client

@enduml