@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as UR
participant ":DisplayListingsUI" as UI
participant ":DisplayListingsUI" as UI
participant ":DisplayListingsController" as CTRL
participant ":Repositories" as reposclass
participant "repositories\n:Repositories" as repositories
participant "listingRepository\n:ListingRepository" as LRepo
participant "listing\n:Listing" as listing



activate UR
UR -> UI: starts listing announcements
activate UI
UI -> CTRL**: create
UI -> CTRL: getAvailableFields()
activate CTRL

CTRL -> reposclass: getInstance()
activate reposclass
reposclass --> CTRL: repositories
deactivate reposclass
CTRL -> repositories: getListingsRepository()
activate repositories
repositories --> CTRL: listingsRepository
deactivate repositories
CTRL -> LRepo: getAvailableFields()
activate LRepo
loop for each listing
LRepo -> listing: isVisible()
activate listing
return true/false
'LRepo -> listing: getBusinessType()
alt true
LRepo -> listing: getListing()
activate listing
return listing
else false
listing --> LRepo: null
end
'listing --> LRepo: businessType
'LRepo -> listing: getPropertyType()
'listing --> LRepo: propertyType
'LRepo -> listing: getNumberOfRooms()
'listing --> LRepo: numberOfRooms
deactivate listing
end
LRepo --> CTRL: availableFields
deactivate LRepo

CTRL -> UI: availableFields
deactivate CTRL

UI --> UR: shows available fields and\nrequests data selection
alt
UR -> UI: selects required data
UI -> CTRL: getListings(businessType,\npropertyType, numberOfRooms)
activate CTRL
CTRL -> LRepo: getListings(businessType,\npropertyType, numberOfRooms)
activate LRepo
loop for each listing
LRepo -> listing: isVisible()
activate listing
return true/false
deactivate listing
LRepo -> listing: isBusinessType(businessType)
activate listing
return true/false
deactivate listing

LRepo -> listing: isPropertyType(propertyType)
activate listing
return true/false
deactivate listing

LRepo -> listing: numberOfRoomsEquals(\nnumberOfRooms)
activate listing
return true/false
deactivate listing


end

LRepo --> CTRL: listings
deactivate LRepo
CTRL --> UI: listings
deactivate CTRL
UI --> UR: shows matching announcements
else
UR -> UI: doesn't select any data
UI -> CTRL: getAllVisibleListings()
activate CTRL
CTRL -> LRepo: getAllVisibleListings()
activate LRepo
loop for each listing
LRepo -> listing: isVisible()
activate listing
return true/false
deactivate listing
end
LRepo --> CTRL: listings
deactivate LRepo

CTRL --> UI: listings
deactivate CTRL
UI --> UR: shows all announcements

end 'ALT fragment end

UR -> UI: selects sorting order
UI -> UI: sort(mode)
UI --> UR: displays sorted data


@enduml