@startuml

Actor UnregisteredUser as user
participant System as ui

autonumber

user -> ui: starts register in the system

ui -> user: request user name

user -> ui: types name

ui -> user: requests user e-mail

user -> ui: types user e-mail

ui -> user: requests user password

user -> ui: types user password

ui -> user: shows typed data and asks for confirmaation

user -> ui: confirms data














































@enduml
