@startuml
'https://plantuml.com/class-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
skinparam groupInheritance 1
hide circle
hide methods




Announcement "1" -- "1" Property: contains >

'Network "1" -- "*" Employee: employs >



'Agent -|> Employee




together {
Client <|-- Buyer
Client <|-- Seller
}

Seller "1" - "*" Property: owns >
Seller "1" - "*" Announcement: creates >
Visit "1" -- "1" Buyer: requests <
Buyer "1" -- "*" Announcement: browses >
'Visit "1" - "1" Agent: scheduled by >



'class Network{

'}



class Client {
name
email
password
cCNumber
TaxNumber
address
phoneNumber
}
class Buyer
class Seller

class Visit{

}

class Announcement{
'listingID
'visible
'price
'commission
'typeOfBusiness
}


class Property{
'area
'city
'cityCenterDistance
'photographs
}





@enduml