@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor Owner as owner
participant ":RegisterPropertyUI" as ui
participant ":RegisterPropertyController" as ctrl
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as rep
participant ":RegisterEmployeeRepository" as repEmp
participant ":PropertyRepository" as repProp
participant ":Property" as property

activate owner

        owner -> ui : starts the request for listing a property

        activate ui

        ui--> owner : requests to select the type of property

        owner -> ui: selects the type of property

        ui -> ctrl** : create

        ui-> ctrl: getAgent()

        activate ctrl

        ctrl -> RepositorySingleton: getInstance()
        activate RepositorySingleton
        RepositorySingleton --> ctrl: repositories
        deactivate RepositorySingleton

        ctrl -> rep: getEmployeeRepository()
        activate rep
        rep--> ctrl: RegisterEmployeeRepository
        deactivate rep

        ctrl ->repEmp: getAgents()
        activate repEmp
        repEmp -> ctrl: agentsList
        deactivate repEmp

        ctrl-> ui: agentsList

        ui --> owner : requests listing and property data

        owner -> ui : inserts the property data

        ui-> owner: validates data

        ui -> ctrl: createProperty()
        ctrl -> repProp: createProperty()
        activate repProp

        repProp -> property **:
        repProp -> repProp: addProperty (Property)
        activate repProp
            repProp -> repProp: validateProperty(Property))
            activate repProp
                repProp --> repProp
            deactivate repProp
            repProp --> repProp
        deactivate repProp

        deactivate repProp

            ctrl --> ui: Announcement
        deactivate ctrl
            ui --> owner: informs operation success
        deactivate ui

deactivate owner


          @enduml