@startuml

@startuml


class Repositories{
}
class RegisterEmployeeRepository{
}
class Property{
    - int propertyID
    - float area
    - String address
    - float cityCentreDistance
    - Arraylist<String> photographs
}
class House{
    - int numberOfBedrooms
    - int numberOfBathrooms
    - int numberOfParkingSpaces
    - Arraylist<String> equipment
    - boolean hasBasement
    - boolean hasInhabitableLoft
    - SunExposure sunExposure
}
class Apartment{
    - int numberOfBedrooms
    - int numberOfBathrooms
    - int numberOfParkingSpaces
    - Arraylist<String> equipment
}
class Land{

}
class RegisterPropertyUI {
    + getAgent()
    + createProperty()

}

class RegisterPropertyController {
    + getInstance()
    + getEmployeeRepository()
    + getAgents()
    + createProperty()
}

class PropertyRepository {
    + addProperty()
    + validateProperty()
}


RegisterPropertyUI --> RegisterPropertyController
RegisterPropertyController --> Repositories
RegisterPropertyController --> RegisterEmployeeRepository
RegisterPropertyController --> PropertyRepository
PropertyRepository --> Property
House --> Property
Apartment --> Property
Land --> Property

@enduml