@startuml

@startuml


class Repositories{
}
class RegisterEmployeeRepository{
}
class Announcement{
    + validateAnnouncement()
    + addAnnouncement()
}
class Property{
    - int propertyID
    - float area
    - String address
    - float cityCentreDistance
    - Arraylist<String> photographs
    + validateProperty()
}
class House{
    - int numberOfBedrooms
    - int numberOfBathrooms
    - int numberOfParkingSpaces
    - Arraylist<String> equipment
    - boolean hasBasement
    - boolean hasInhabitableLoft
    - SunExposure sunExposure
}
class Apartment{
    - int numberOfBedrooms
    - int numberOfBathrooms
    - int numberOfParkingSpaces
    - Arraylist<String> equipment
}
class Land{

}
class RegisterPropertyUI {
    + getAgent()
    + createAnnouncement()

}

class RegisterPropertyController {
    + getInstance()
    + getEmployeeRepository()
    + getAgents()
    + createProperty()
    + createAnnouncement()
}

class AnnouncementRepository {
    + createAnnouncement()
}


RegisterPropertyUI --> RegisterPropertyController
RegisterPropertyController --> Repositories
RegisterPropertyController --> RegisterEmployeeRepository
RegisterPropertyController --> AnnouncementRepository
RegisterPropertyController --> Property

House --> Property
Apartment --> Property
Land --> Property
AnnouncementRepository --> Announcement

@enduml