@startuml

title System Sequence Diagram US010

actor Client as client
participant System as ui

autonumber

activate client
activate ui

client -> ui: starts placing an order to purchase the property

ui -> client: shows announcements list and requests the user to select one

client -> ui: selects announcement with the desire property

loop (order amount is not equal or lower than the price of the property)

        ui -> client: requests order amount
        client -> ui: types order amount

end

ui -> client: shows the order data and asks for confirmation

client -> ui: confirms the data

ui -> client: informs operation sucess


@enduml