@startuml

@startuml

class Employee {
    - String name
    - int citizenCardNumber
    - int taxNumber
    - String address
    - String emailAddress
    - int telephoneNumber
    - String agency
    + saveEmployee()

}

class RegeisterEmployeeUI {
    + registerEmployee()

}

class RegeisterEmployeeController {
    + createEmployee()
}

class EmployeeRepository {
    + showEmployee()

}

Enum Role {

    ADMINISTRATOR
    MANAGER
}

Enum Agency {

    AGENCY1
    AGENCY2
    AGENCY3
}

RegeisterEmployeeUI --> RegeisterEmployeeController
RegeisterEmployeeController --> Employee
Employee --> Role
Employee --> Agency
Employee --> EmployeeRepository


@enduml