@startuml

interface Runnable {
    + run()
}

class ValidateVisitUI {
    - controller
}

class ScheduleVisitController {
    - ScheduleRepository
    + getScheduleList()
    + addConfirmedVisit()
    + sendValidationEmail()
    + getAgentFromSession()
}

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserNameByEmail()
}
class Schedule {

    - name
    - phoneNumber
    - announcement
    - day
    - begiHour
    - endHour
    - note
    - status
}
class Repositories {

    + scheduleRepository
}
class ScheduleRepository {

    - ScheduleList
    - ConfirmedScheduleList
    + addConfirmedVisit()
    + removeFromRequestSchedule()
    + getScheduleList()
    + getScheduleListAsString()
}


Runnable -left-|> ValidateVisitUI
ApplicationSession -> ApplicationSession : instance
ApplicationSession --> "1" UserSession : userSession
ScheduleVisitController ..> ApplicationSession
ScheduleVisitController ..> UserSession

ValidateVisitUI ..> ScheduleVisitController
ScheduleVisitController -> Repositories
Repositories -> ScheduleRepository

ScheduleRepository --> Schedule

@enduml