@startuml

interface Runnable {
    + run()
}

class ValidateScheduleGUI {
    + start()
    + main()
}


class ScheduleVisitController {

    - ScheduleRepository
    - ScheduleAnswer
    - btnSubmit
    - rbAcceptSchedule
    - rbRejectSchedule
    - rowBeginHour
    - rowClientName
    - rowDay
    - rowEndHour
    - rowLocation
    - rowNote
    - rowPrice
    - rowTypeOfBusiness
    - tblScheduleList
    + initialize()
    + submit()
    + getRequestScheduleListByResponsibleAgent()
    + addConfirmedSchedule()
    + addRejectedSchedule()
    + sendEmail()
}

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserNameByEmail()
}
class Schedule {

    - name
    - phoneNumber
    - announcement
    - day
    - begiHour
    - endHour
    - note
    - status
}
class Repositories {

    + scheduleRepository
}
class ScheduleRepository {

    - ScheduleList
    - schedulesByResposibleAgent
    + addConfirmedSchedule()
    + addRejectedSchedule()
    + getRequestScheduleListByResponsibleAgent()
    + readObjectScheduleRequest()
    + writeObjectScheduleRequest()

}


Runnable -left-|> ValidateScheduleGUI
Application -right-|> ValidateScheduleGUI
ApplicationSession -> ApplicationSession : instance
ApplicationSession --> "1" UserSession : userSession
ScheduleVisitController ..> ApplicationSession
ScheduleVisitController ..> UserSession

ValidateScheduleGUI ..> ScheduleVisitController
ScheduleVisitController .right.> Repositories
Repositories .right.> ScheduleRepository

ScheduleRepository --> Schedule

@enduml