@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}


class Employee {
    name
    email
    position
    phone
}


'class User {
'    name
'    email
'    password
'}

/'class Agent {

}

class Property {

}

class House {

}

class Apartment {

}

class Land {

}

class Client {

}

class Listing {

}

class "Unregistered User" {

}'/


House --|> Property
Apartment --|> Property
Land --|> Property
Listing "1" -- "1" Property: includes >

Agent --|> Employee
'Employee -|> User
Agent "1" -- "*" Listing: validates >
'Client "0..1" - "*" Property: owns >
Property "*" - "1" Client : owns <
'Client "*" -|> "1" User
Client "1" -- "*" Listing: creates >
'"Unregistered User" "1" ---|> "1" User
"Unregistered User" "1" -- "*" Listing: browses >

@enduml