@startuml

class Branch {

    - int ID
    - String name
    - String location
    - int phoneNumber
    - String email


    + checkIfDataIsNull()
    + checkNameLength()
    + checkValidEmail()
    + checkValidPhoneNumber()



}

class RegisterBranchUI {


}

class RegisterBranchController {

    + createBranch()
}

class Repository {
    - Repositories()
    + getBranchRepository()
}


class BranchRepository {

   
}


RegisterBranchUI -[dashed]-> RegisterBranchController
RegisterBranchController -[dashed]-> Repository
Repository --> BranchRepository
BranchRepository --> Branch


@enduml