@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam shadowing false
autonumber

actor "System Administrator" as sa
participant ":LegacyImportUI" as ui
participant ":LegacyImportController" as ctrl
participant ":FileHandler" as fh
participant ":Repositories" as repos
participant "repositories\n:Repositories" as repositories
participant "announcementRepository\n:AnnouncementRepository" as ARepo
participant "employeeRepository\n:EmployeeRepository" as ERepo
participant "clientRepository\n:ClientRepository" as CRepo
participant ":Announcement" as announcement
participant ":Property" as prop

activate sa
sa -> ui: starts importing data
activate ui
ui -> ctrl**: create
activate ctrl
ctrl -> repos: getInstance()
activate repos
return repositories

ctrl -> repositories: getAnnouncementsRepository()
activate repositories
return announcementRepository

ctrl -> repositories: getEmployeesRepository()
activate repositories
return employeeRepository

ctrl -> repositories: getClientsRepository()
activate repositories
return clientRepository
deactivate ctrl

return requests file path

sa -> ui: types file path
activate ui

ui -> ctrl: importFile(filePath)
activate ctrl
'ctrl -> fh**: create
ctrl -> fh: readFile(filePath)
activate fh
return file

ctrl -> fh: readCSV(file)
activate fh
return csv[]

ctrl -> ERepo: getEmployeeByName("Legacy Agent")
activate ERepo
alt
    ERepo --> ctrl: Employee legacyAgent
else
    return null
    ctrl -> ERepo: registerEmployee
    activate ERepo
    return true
end


ctrl -> fh: parseCsv
ctrl -> fh: getEntry
ctrl -> fh: parseAnnouncementData
ctrl -> fh: parsePropertyData
ctrl -> fh: parseBranchData
ctrl -> fh: parseClientData


alt
    ui --> sa: informs operation success
else
    ui --> sa: inform no CSV file found
else
    return inform file is empty

end

deactivate sa

@enduml