@startuml

title Domain Model US020

object Client {

}

object Schedule {

}

object Announcement {

}

object Property {

}

object House {


}

object Apartment {

}

object Land {

}

object Commission {

}

object FixedCommission {

}

object PercentageCommission {

}

Client -> Schedule: read the response

Announcement "1" -- "1" Property: contains >
Announcement "1" ---> "1" Commission: has a >

Property <|-- House
Property <|-- Apartment
Property <|-- Land

Commission <|-- FixedCommission
Commission <|-- PercentageCommission

Schedule --> Property: to visit >

@enduml
