@startuml


class ReadResponseOfAppointmentRequestGUI {

}

class ReadResponseOfAppointmentRequestController {

}

class Repositories {

}

Application -left-|> ReadResponseOfAppointmentRequestGUI


@enduml