@startuml

interface Runnable {

    + run()
}

class PlaceOrderToBuyPropertyUI {

    - controller
}

class PlaceOrderToBuyPropertyController {

    - orderRepository
    + createOrder()
    + getAnnouncementList()
}

class Order {

    - client
    - orderAmount
    - announcement
    - status
}

class PlaceOrderToBuyPropertyRepository {

    - orderList
    + seveOrder()
    + validateOrder()
    + addOrder()
    + getOrderList()
    + getOrdersListAsString()
}

class AnnouncementRepository {

    + save()
    + createAnnouncement()
    + validateAnnouncement()
    + addAnnouncement()
    + getAllVisibleAnnouncements()
    + getAvailableFields()
    + getAnnouncements()
}

class AnnouncementDTO {

    - price
    - typeOfBusiness
    - property
    - agent
}

class AnnouncementMapper {

    - announcementDTOList
    + convert()
    + toDto()
    + getAllAnnouncements()
    + getAnnouncementDTOById()
    + toDtoAnnouncement()
}

class Repositories {

    + announcementRepository
}

class Announcement {

}



Runnable -left-|> PlaceOrderToBuyPropertyUI
PlaceOrderToBuyPropertyUI ..> PlaceOrderToBuyPropertyController
PlaceOrderToBuyPropertyController ..> Repositories
PlaceOrderToBuyPropertyController ..> AnnouncementRepository
Repositories -> AnnouncementRepository
Repositories -> PlaceOrderToBuyPropertyRepository
PlaceOrderToBuyPropertyController ..> AnnouncementMapper
PlaceOrderToBuyPropertyController ..> PlaceOrderToBuyPropertyRepository
AnnouncementMapper --> AnnouncementDTO
Order --> PlaceOrderToBuyPropertyRepository

@enduml