@startuml

title Sequence Diagram US010

actor Client as client
participant PlaceOrderToBuyPropertyUI as ui
participant PlaceOrderToBuyPropertyController as ctr
participant AnnouncementMapper
participant AnnouncementDTO
participant AnnouncementRepository
participant Repositories
participant PlaceOrderToBuyPropertyRepository
participant Order as order

autonumber

activate client

client -> ui: starts placing an order to purchase the property

activate ui

ui -> ctr** : create

ui -> ctr: getAnnouncementList()

deactivate ui
activate ctr

ctr -> Repositories: getAnnouncementList()

deactivate ctr
activate Repositories

Repositories -> AnnouncementRepository: return AnnouncementList

deactivate Repositories
activate AnnouncementRepository

AnnouncementRepository -> AnnouncementDTO: return AnnouncementList

deactivate AnnouncementRepository
activate AnnouncementDTO

AnnouncementDTO -> AnnouncementMapper: return AnnouncementList

deactivate AnnouncementDTO
activate AnnouncementMapper

AnnouncementMapper -> ctr:  return AnnouncementList

deactivate AnnouncementMapper
activate ctr

ctr -> ui: return AnnouncementList

deactivate ctr
activate ui

ui -> client: shows Announcement list and requests the user to select one

client -> ui: selects Announcement with the property

loop (when order amount is not equal or lower than the price of the property)

    ui -> client: requests order amount
    client -> ui: types order amount

end

ui -> ctr: createOrder()

deactivate ui
activate ctr

ctr -> order: createOrder()

deactivate ctr
activate order

order -> order: validates

order -> ctr: return created order

deactivate order
activate ctr

ctr -> ui: return created order

deactivate ctr
activate ui

ui -> client: shows selected property and the order amount and asks for confirmation

client -> ui: confirms the data

ui -> ctr: saveOrder()

activate ctr

ctr -> PlaceOrderToBuyPropertyRepository: saveOrder()

deactivate ctr
activate PlaceOrderToBuyPropertyRepository

ui -> client: informs operation sucess

deactivate client

@enduml