@startuml
autonumber
title User specifies a new location

actor User
participant UI
participant Controller
participant Repository




alt Invalid input
    activate Controller
    Controller -> UI: displayErrorMessage("Invalid state input. Please try again.")
    deactivate Controller
    loop until valid input provided
        User -> UI: inputs state
        activate UI
        UI -> Controller: createState(state)
        deactivate UI
        activate Controller
        activate Repository
        Controller -> Repository : validate(state)
        Repository -> Controller : returns outcome of the operation
        deactivate Repository
        
    end
end

Repository --> Controller: save(state)
deactivate Repository

deactivate Controller


@enduml
