@startuml

:System Administrator: as Admin
:Unregistered User: as UnregUser
:Agent: as Agent
:Owner: as Owner

Left to right direction

UnregUser --> (US001: display listed properties)

Agent --> (US002: publish any sale announcement on the system)

Admin --> (US003: register a new employee)

Owner --> (US004: submit a request for listing a property sale or rent, choosing the responsible agent)

Admin --> (US005: register a store)

Admin --> (US006: specify districts, municipalities, and parishes in the system)

UnregUser --> (US007: register in the system to buy, sell or rent properties)

@enduml