@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US015(SSD) - List all booking requests managed by agent

autonumber

actor "Agent" as agent
participant ":System" as System

    activate agent
    agent -> System : asks to list all booking request managed by me
    activate System
    System --> agent : requests to select begin date and end date
    deactivate System
    agent -> System : selects begin date and end date
    activate System
    System --> agent : shows sorted list of booking requests
    deactivate System

deactivate agent
@enduml