@startuml

class SystemAdministrator {
}

class Employee {
    - String name
    - int taxNumber
    - int taxNumber
    - String address
    - String emailAddress
    - int telephoneNumber
    - Role role
    - Angency agency
}

SystemAdministrator -> Employee: Registers





















@enduml