@startuml

actor Administrator as adm
participant ":RegisterEmployeeUI" as ui
participant ":RegisterEmployeeController" as ctr
participant Employee as em
participant Role as role
participant Agency as agency
participant ":EmployeeRepository" as rp

autonumber

activate adm

        adm -> ui: starts registering a new employee

        activate ui

        ui -> ctr** : create

        deactivate ui

        adm <- ui: requests employee data

        activate ui

        adm -> ui: types employee data

        ui -> ctr: registerEmployee

        deactivate ui
        activate ctr

        ctr -> em: createEmployee(name,\n passportNumber,\n tax number, address, e-mail,\n telephoneNumber)

            deactivate ctr
            activate em

            em -> em: validate data

        ui -> ctr: getRoleList()

        activate ui
        activate ctr
        deactivate em

        ctr -> role: getRoleList()
        activate role
        deactivate ui

        role -> ctr: return Role list

        deactivate role

        ctr -> ui: return Role list
        deactivate ctr

        activate ui

        ui -> adm: shows role list and asks the user to select one

        adm -> ui: select a role

        ui -> ctr: saveEmployeeRole
        deactivate ui
        activate ctr

        ctr -> em: saveEmployeeRole

        activate em

        ui -> ctr: getAgencyList()

        activate ui

        deactivate em

        ctr -> agency: getAgencyList()

        activate agency
        deactivate ui

        agency -> ctr: return Agency list

        deactivate agency

        ctr -> ui: return Agency list

        deactivate ctr
        activate ui

        ui -> adm: shows agency list and asks the user to select one

        adm -> ui: select agency

        ui -> ctr: saveEmployeeAgency()

        deactivate ui

        ctr -> em: saveEmployeeAgency()
        activate ctr
        activate em

        deactivate em

        deactivate rp

        ctr -> ui: return RegisteredEmployee

        deactivate ctr
        activate ui

        adm <- ui: shows employee data and asks confirmation

        deactivate ui

        adm -> ui: confirms the data

        activate ui

        ui -> ctr: saveEmployee()

        activate ctr
        deactivate ui

        ctr -> rp: saveEmployee()

        activate rp
        deactivate rp

        adm <- ui: informs operation sucess

        activate ui

        deactivate ui

deactivate adm


@enduml